language: node_js
node_js:
  - "v6.9.2"

services:
  - postgresql

postgres:
  adapter: postgresql
  database: everreal-tests
  username: postgres
  password: password

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - "yarn install"
  - psql -c 'create database "everreal-tests";' -U postgres

script:
  - "yarn lint"
  - "yarn test-once"
