#!/bin/sh

IMAGE_NAME=docker-registry.everreal.co/er-web/er-heimdall

docker login docker-registry.everreal.co -u ${ER_DOCKER_REGISTRY_USERNAME} -p ${ER_DOCKER_REGISTRY_PASSWORD}

echo "=====> BUILDING $IMAGE_NAME:$VERSION"
VERSION=latest
docker build -t "$IMAGE_NAME:$VERSION" .

echo "=====> BUILDING $IMAGE_NAME:$VERSION"
VERSION=$(docker run "$IMAGE_NAME:latest" node -e "console.log(require('./package.json').version)")
docker build -t "$IMAGE_NAME:$VERSION" .

echo "=====> PUSHING $IMAGE_NAME:$VERSION"
VERSION=$(docker run "$IMAGE_NAME:latest" node -e "console.log(require('./package.json').version)")
docker push "$IMAGE_NAME:$VERSION"

echo "=====> PUSHING $IMAGE_NAME:$VERSION"
VERSION=latest
docker push "$IMAGE_NAME:$VERSION"
